services:

    caldav-reminder-telegram-bot: &caldav-anchor
      image: docker.io/mcdax/caldav-reminder-telegram-bot:latest
      environment: # documentation: https://github.com/mcdax/caldav-reminder-telegram-bot
        CALDAV_URL: "${CALDAV_URL}"
        CALDAV_USERNAME: "${CALDAV_USERNAME}"
        CALDAV_PASSWORD: "${CALDAV_PASSWORD}"
        CALENDAR_IDS: "${CALENDAR_IDS}"
        SYNC_INTERVAL_IN_SEC: "${SYNC_INTERVAL_IN_SEC:-600}"
        FETCH_EVENT_WINDOW_IN_DAYS: "${FETCH_EVENT_WINDOW_IN_DAYS:-1}"
        TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
        TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
        TIMEZONE: "${TIMEZONE:-Europe/Moscow}"
      restart: unless-stopped  # Restart policy
