#!/bin/sh -e

trap 'echo Error code ${?} at line ${LINENO}: "${BASH_COMMAND:-BASH_COMMAND is empty}"' ERR

[ ! -z "${BOT}" ]           # exit if no bot selected
cd "$(dirname ${0})/${BOT}" # enter workdir named as BOT

alias stop='podman-compose down'
alias start='exec podman-compose --podman-run-args="--sdnotify=conmon" up --force-recreate'
# Status is mostly useless. Watch ExecStartPost in composectl@.service.
alias status='
 readonly CONTAINERS=$(podman-compose ps --quiet);
 [ ! -z "${CONTAINERS}" ];
 for c in ${CONTAINERS}; do podman healthcheck run "${c}"; done;
'

case "${1}" in
 # NB! call start *after* all commands, becuase of using exec call in start
 'restart' ) stop && sleep 5s && start;;
 'start'   ) start;;
 'stop'    ) stop;;
 'status'  ) status;;
 *         ) echo "USAGE: BOT='${BOT:-botdir}' ${0} [ start | stop | status | restart ]" >&2;;
esac
